### ISSUE TITLE
Makefile improvements 

### ISSUE THREAD

**Issue by alimon** [rdleon/netdrive#1]
From 36e414bbc16909d3568ae2a2020cb7049903e5e1 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?An=C3=ADbal=20Lim=C3=B3n?= <anibal.limon@linux.intel.com>
Date: Fri, 28 Aug 2015 14:24:33 -0500
Subject: [PATCH] Makefile: Use c11 standard and be pedantic when compile.
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Signed-off-by: Aníbal Limón <anibal.limon@linux.intel.com>
---
 Makefile | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index d8031ed..b76dbec 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,6 @@
 CC=gcc
-CFLAGS=-g -Wall
+DEBUG=-g3
+CFLAGS=-Wall -Werror -std=c11 -pedantic $(DEBUG)
 
 all: netdrive
 
-- 
1.9.1

**Comment by rdleon** [comment]
This was integrated in master@4d647f4b7680268ddf76145b8d88917b3ff1a6a7
